version: '3.8'

services:
  app:
    image: ricoroenaldo94/sparc-ci4
    container_name: ci4_app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - CI_ENVIRONMENT=production
    volumes:
      - .:/var/www/html
    restart: always

  db:
    image: mysql:8.0
    container_name: ci4_db
    platform: linux/arm64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4login
      MYSQL_USER: ci4_user
      MYSQL_PASSWORD: ci4_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  db_data:
